version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout

      - run:
          name: Install Dependencies
          working_directory: ~/project/work/calcdemo/
          command: poetry install

      - run:
          name: Exec pytest
          working_directory: ~/project/work/calcdemo/
          command: |
            poetry run pytest --cov=. --cov-report=html
            cp -r htmlcov /tmp/
      
      - run:
          name: copy artifacts
          working_directory: ~/project/work/calcdemo/
          command: |
            ls -la
            cp -r htmlcov /tmp/
            
      - store_artifacts:
          path: /tmp/htmlcov
