version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout

      - run: |
           pwd
           ls -la

      - restore_cache:
          keys:
            - deps-{{ checksum "work/calcdemo/poetry.lock" }}

      - run:
          working_directory: ~/work/calcdemo/
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: deps-{{ checksum "work/calcdemo/poetry.lock" }}
          paths:
            - ./work/calcdemo/

      - run:
          name: Exec pytest
          command: |
            poetry run pytest
            source $(find . -name circleci-poetry*)/bin/activate
            pytest
