version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "~/project/work/calcdemo/poetry.lock" }}

      - run:
          name: Install Dependencies
          working_directory: ~/project/work/calcdemo/
          command: poetry install

      - save_cache:
          key: deps-{{ checksum "~/project/work/calcdemo/poetry.lock" }}
          paths:
            - ~/project/work/calcdemo/

      - run:
          name: Exec pytest
          working_directory: ~/project/work/calcdemo/
          command: |
            poetry run pytest --cov=. --cov-report=html
            cp -r htmlcov /tmp/

      - store_artifacts:
          path: /tmp/htmlcov
