version: 2
jobs:
  build:
    working_directory: ~/work/calcdemo
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout

      - run: ls -la

      - restore_cache:
          keys:
            - deps-{{ checksum "~/work/calcdemo/poetry.lock" }}

      - run:
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: deps-{{ checksum "~/work/calcdemo/poetry.lock" }}
          paths:
            - ~/work/calcdemo 

      - run:
          name: Exec pytest
          command: |
            poetry run pytest
            source $(find . -name circleci-poetry*)/bin/activate
            pytest
